import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    private static final Logger LOGGER = LoggerFactory.getLogger(Library.class);

    public int add(int a, int b) {
        LOGGER.info("a + b = {}", a + b);
        return a + b;
    }

    public boolean isNegative(int a) {
        return a < 0;
    }

    public String isEvenOrOdd(int a) {
        return a % 2 == 1 ? "Odd" : "Even";
    }
}
