/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void addShouldAddTwoIntegers() {
        Library classUnderTest = new Library();
        int expected = 2;
        assertEquals("add should add two integers", expected, classUnderTest.add(1, 1));
    }

    @Test public void isNegativeShouldReturnTrueWhenNegative() {
        Library classUnderTest = new Library();
        int input = -1;

        assertTrue("isNegative should return True for negative input", classUnderTest.isNegative(input));
    }

    @Test public void isNegativeShouldReturnFalseWhenPositive() {
        Library classUnderTest = new Library();
        int input = 1;

        assertFalse("isNegative should return False for positive input", classUnderTest.isNegative(input));
    }

    @Test public void isEvenOrOddShouldReturnEvenWhenEven() {
        Library classUnderTest = new Library();
        int input = 4;
        String expected = "Even";

        assertEquals("isEvenOrOdd returns Even for an even input", expected, classUnderTest.isEvenOrOdd(input));
    }

    @Test public void isEvenOrOddShouldReturnOddWhenOdd() {
        Library classUnderTest = new Library();
        int input = 3;
        String expected = "Odd";

        assertEquals("isEvenOrOdd returns Odd for an odd input", expected, classUnderTest.isEvenOrOdd(input));
    }
}
